#!/bin/sh

# INSTALL TO PRODUCTION SCRIPT

INST_PATH="c\$/foxdata"
MARKER_PATH=$INST_PATH/mark
LIB="/cygdrive/c/home/lib"

for SRV in BORIS64 LIST5 LIST8 PRODUCTION1 PRODUCTION2 PRODUCTION3 PRODUCTION5 PRODUCTION6 PRODUCTION7 PRODUCTION8 PRODUCTION9 PRODUCTION11 PRODUCTION13 PRODUCTION14 PRODUCTION15 PRODUCTION17 PRODUCTION18 PRODUCTION19 PRODUCTION20 PRODUCTION21 PRODUCTION22 PRODUCTION23 PRODUCTION24 PRODUCTION25 PRODUCTION26 PRODUCTION27 PRODUCTION28 PRODUCTION29 PRODUCTION30 PRODUCTION31 PRODUCTION32 PRODUCTION33
do
    echo
    echo $SRV

    if [ ! -d //$SRV/$MARKER_PATH ]; then
        mkdir //$SRV/$MARKER_PATH
        chmod 777 //$SRV/$MARKER_PATH
    fi

    # TO FOXDATA:
    cp *PRG //$SRV/$INST_PATH
    cp foxwrap.py //$SRV/$INST_PATH

    # TO FOXDATA/instdir
    cp $LIB/*py //$SRV/$MARKER_PATH    
    cp *py //$SRV/$MARKER_PATH
done

